### ISSUE TITLE
npm 包 one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by tiyunchen** [huaweicloud/huaweicloud-sdk-browserjs-obs#10]
出现
`only one instance of babel-polyfill is allowed `
这个问题

**Comment by tiyunchen** [comment]
使用 esdk-obs-browserjs-without-polyfill-3.19.9.min.js 就可以了

**Comment by wuchengqi577** [comment]
您好，非常感谢你的issue问题，如果没有问题了，麻烦Close掉这个issue，谢谢

**Comment by NoAccident** [comment]
由于该问题1个月内未收到任何进一步反馈，因此暂时关闭问题，后续仍存在该问题请重新提issue咨询。
