### ISSUE TITLE
上传过程中，怎么中断请求

### ISSUE THREAD

**Issue by gaochao0411** [huaweicloud/huaweicloud-sdk-browserjs-obs#16]
我上传文件，上传过程中，我叉掉上传，可是请求没中断，我要怎么中断请求呢

**Comment by NoAccident** [comment]
您好，目前支持断点续传中断请求，相关demo链接：https://support.huaweicloud.com/sdk-browserjs-devg-obs/obs_24_1715.html

**Comment by gaochao0411** [comment]
好吧，其他的不支持是吧

**Comment by NoAccident** [comment]
https://github.com/huaweicloud/huaweicloud-sdk-browserjs-obs/issues/13 可以参考这个问题的解决思路，再使用axios来取消请求

**Comment by gaochao0411** [comment]
好的，谢谢
