### ISSUE TITLE
如何使用obsclient忽略ssl证书校验？

### ISSUE THREAD

**Issue by ncistyang** [huaweicloud/huaweicloud-sdk-browserjs-obs#29]
我们去对接了某个hcso的私有云的对象存储，但是该私有云客户没有买证书，导致页面上请求报错如下：
HEAD https://sf9221828546444581c6217994faeaec.obs.region.xxxx.com/?apiversion net::ERR_CERT_AUTHORITY_INVALID

请问我们如何在调用过程中忽略ssl证书校验呢。

**Comment by NoAccident** [comment]
浏览器在发送HTTPS请求的时候会检查服务器提供的证书，检查证书是否由受操作系统/浏览器信任的证书签发机构签发。您当前的HCSO局点没有提供这种正式证书。

建议咨询对应环境的局点管理员/交付人员，将给OBS签发证书的自签名证书机构的根证书导入到用户PC中，可以永久解决这个问题。

![image](https://user-images.githubusercontent.com/87176703/195777691-2a598a60-cd8b-4d79-8390-a8daf64b5dfd.png)
