### ISSUE TITLE
使用sdk的断点续传的暂停会报错，但是不影响使用，恢复上传会全部重新上传

### ISSUE THREAD

**Issue by hj-long** [huaweicloud/huaweicloud-sdk-browserjs-obs#39]
我点击取消之后，调用obsClient.uploadFile的ProgressCallback回调里触发：hook.cancel();
但是会报错： 
![image](https://github.com/huaweicloud/huaweicloud-sdk-browserjs-obs/assets/90207875/ce129b57-bd28-49c7-89a6-510cf443b011)
然后我继续点击恢复上传，会把文件重新进行上传，而不是停留在上一次的记录

**Comment by zhangtingwei998** [comment]
browserjs sdk uploadFile方法的断点续传内容是存在内存中的，所以只能通过代码判断是否失败，并重试。重新手动触发uploadFile方法无法获取到之前的断点续传内容

**Comment by zhangtingwei998** [comment]
> 之后我点击取消，调用obsClient.uploadFile的ProgressCallback回调里触发：hook.cancel(); 但是会报错： 然后我继续点击上传，把文件重新进行上传，而不是停留在上一次的记录 ![图像](https://user-images.githubusercontent.com/90207875/275409016-ce129b57-bd28-49c7-89a6-510cf443b011.png)

**Comment by zhangtingwei998** [comment]
> 我点击取消之后，调用obsClient.uploadFile的ProgressCallback回调里触发：hook.cancel(); 但是会报错： ![image](https://user-images.githubusercontent.com/90207875/275409016-ce129b57-bd28-49c7-89a6-510cf443b011.png) 然后我继续点击恢复上传，会把文件重新进行上传，而不是停留在上一次的记录
