### ISSUE TITLE
元数据Cache-Control

### ISSUE THREAD

**Issue by tianwening** [huaweicloud/huaweicloud-sdk-browserjs-obs#5]
你好，我这面上传的时候尝试在元数据里面塞入Cache-Control的元数据， 但是获取对象资源的时候这个头返回的是x-obs-meta-cache-control: no-cache这个加了前缀的，这个是啥原因？我主要是想在canvas将图片资源绘制出来，然后通过转换成图片的形式导出，请教下上传对象的话应该怎么做后续可以避免绘制中出现的跨域问题？

**Comment by JMD110** [comment]
你是通过设置对象元数据接口设置的Cache-Control? 不要加载metadata中, 参数为CacheControl
https://github.com/huaweicloud/huaweicloud-sdk-browserjs-obs/blob/951327efbc9b15cdad96c9136ecf15e86d908f0a/src/scripts/obsModel.js#L2802

**Comment by JMD110** [comment]
跨域设置中有一个缓存时间 
![image](https://user-images.githubusercontent.com/37887115/96232065-770bbb00-0fca-11eb-9268-aa6e3eab657f.png)
