### ISSUE TITLE
使用

### ISSUE THREAD

**Issue by 20153403349** [huaweicloud/huaweicloud-sdk-browserjs-obs#8]
我使用npm的方式下载了sdk，然后按照官方示例，但是不起作用，我想知道在vue中var ObsClient = require('esdk-obs-nodejs');该语段之前还需要import操作吗？

**Comment by wuchengqi577** [comment]
您好，esdk-obs-nodejs的仓库地址是[这个](https://github.com/huaweicloud/huaweicloud-sdk-nodejs-obs)，如果有问题可以去这个仓库下提issue，谢谢。

**Comment by NoAccident** [comment]
由于该问题1个月内未收到任何进一步反馈，因此暂时关闭问题，后续仍存在该问题请重新提issue咨询
