### ISSUE TITLE
使用 BrowserJS 删除文件, 文件变成 0byte 空文件

### ISSUE THREAD

**Issue by purpledong** [huaweicloud/huaweicloud-sdk-browserjs-obs#9]
如题, 方法返回删除成功, 但是进 obs browser+ 看, 文件还在, 只是文件大小变成 0byte

**Comment by wuchengqi577** [comment]
你好，根据你的描述不能定位出问题，可以提供一下出现错误的详细步骤（代码）嘛。
如果方便的话，麻烦提供一下demo方便定位问题

**Comment by NoAccident** [comment]
由于该问题1个月内未收到任何进一步反馈，因此暂时关闭问题，后续仍存在该问题请重新提issue咨询
